services:
  api:
    build: .
    container_name: pet-sitter-api-container
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 8000
      AZURE_STORAGE_CONTAINER_NAME: pet-images
      FRONTEND_URL: https://www.whiskarz.com/
    restart: unless-stopped